### ISSUE TITLE
招聘详情抓取

### ISSUE THREAD

**Issue by frameZhang** [zsqosos/positionAnalysis#1]
我想请教怎么抓取招聘的详情，我直接在拉钩上现在找不到请求

**Comment by zsqosos** [comment]
直接请求这个地址：https://www.lagou.com/jobs/positionAjax.json?needAddtionalResult=false&city=%E5%8C%97%E4%BA%AC&kd=php&pn=1
`city`是所有请求的城市名，`kd`是所有请求的关键字，`pn`是要请求的页数，请求的时候尽可能模仿浏览器，所以最好把cookie也加上
